# Generated by Django 4.0.1 on 2022-01-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=16)),
                ('counter', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=16)),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('code', models.CharField(max_length=10)),
                ('expire_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
